#!/bin/bash
# enable color support of ls and also add handy aliases
if [ "$TERM" != "dumb" ] && [ -x /usr/bin/dircolors ]; then
    eval "`dircolors -b`"
    alias ls='ls --color=auto'
    #alias dir='ls --color=auto --format=vertical'
    #alias vdir='ls --color=auto --format=long'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'
alias e="emacs -nw --eval \"(setq frame-background-mode 'dark)\""
alias n="ncmpc -c"

#Load Aliases Present
FIQ=~/environment/bash/svn-aliases
	if [ -f $FIQ ]; then
		. $FIQ
		$LOADED_FILES="$LOADED_FILES:$FIQ"
	fi
